version: '3.7'
organizationservice:
  image: ostock/organization-service:0.0.1-SNAPSHOT
  environment:
    PROFILE: "dev"
    CONFIGSERVER_URI: "http://configserver:8071"
    CONFIGSERVER_PORT:   "8071"
    DATABASESERVER_PORT: "5432"
    ENCRYPT_KEY: "bd5cae3b97d93e385232afd4c0ea92377a193328"
  depends_on:
    database:
      condition: service_healthy
    configserver:
      condition: service_started
  ports:
    - "8081:8081"
  networks:
    - backend