version: '3.7'

services:
  organizationservice:
    image: ostock/organization-service:0.0.1-SNAPSHOT
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8081:8081"
    networks:
      backend:
        aliases:
          - "organizationservice"
networks:
  backend:
    driver: bridge